const KEY="englishRPG_v2";
const LEVELS=[["Tutorial Village",0,500],["English Survivor",500,1500],["Traveler",1500,3000],["Social Zone",3000,6000],["American Conversation",6000,10000],["English Main Character",10000,Infinity]];
const QUESTS=[["Introduce Yourself","Расскажи о себе 60–90 секунд: откуда ты, чем занимаешься, что любишь и зачем учишь английский.",50,"speaking"],["Yesterday Quest","Расскажи 60 секунд о вчерашнем дне. Используй минимум 5 глаголов в Past Simple.",50,"grammar"],["USA Dream","Объясни 60 секунд, почему хочешь поехать в США и что хочешь там увидеть.",50,"speaking"],["Question Hunter","Придумай 5 вопросов человеку из США. Не копируй готовые вопросы.",50,"speaking"],["Daily Life","Опиши свою обычную неделю: учеба, работа, гитара, спорт, друзья.",50,"grammar"],["Story Mode","Расскажи маленькую историю из жизни с началом, событием и концом.",60,"speaking"]];
const BASE={xp:0,stats:{speaking:1,listening:1,vocab:1,grammar:1},streak:0,lastDay:null,quest:0,doneDate:null,enemies:{want:{name:"Want Goblin",hits:0},past:{name:"Past Tense Goblin",hits:0},be:{name:"Be Monster",hits:0},prep:{name:"Preposition Slime",hits:0},questions:{name:"Question Hydra",hits:0}},loot:[{phrase:"I want to + verb",uses:0},{phrase:"I'm trying to + verb",uses:0},{phrase:"I'm going to + verb",uses:0}],settings:{endpoint:"https://api.openai.com/v1/chat/completions",model:"gpt-5-mini",key:""}};
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]=="object"&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a}
function load(){try{return merge(structuredClone(BASE),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return structuredClone(BASE)}}let s=load(),$=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(s))}function today(){return new Date().toISOString().slice(0,10)}
function lvl(){let i=LEVELS.findIndex(x=>s.xp>=x[1]&&s.xp<x[2]);return i<0?5:i}
function markDay(){let t=today();if(s.lastDay===t)return;let d=new Date();d.setDate(d.getDate()-1);let y=d.toISOString().slice(0,10);s.streak=s.lastDay===y?s.streak+1:1;s.lastDay=t;s.doneDate=null}
function gain(n,stat){let before=lvl();markDay();s.xp+=n;if(stat)s.stats[stat]++;save();render();toast(lvl()>before?"🎉 LEVEL UP!":"+"+n+" XP")}
function render(){let i=lvl(),L=LEVELS[i],p=L[2]===Infinity?100:(s.xp-L[1])/(L[2]-L[1])*100;$("levelBadge").textContent=i+1;$("levelName").textContent=L[0];$("xpTotal").textContent=s.xp;$("xpBar").style.width=Math.max(0,Math.min(100,p))+"%";$("xpCaption").textContent=`${Math.max(0,s.xp-L[1])} / ${L[2]===Infinity?"MAX":L[2]-L[1]} XP`;["speaking","listening","vocab","grammar"].forEach(x=>$(x).textContent=s.stats[x]);$("streak").textContent=s.streak;let q=QUESTS[s.quest%QUESTS.length];$("questTitle").textContent=q[0];$("questText").textContent=q[1];$("questXp").textContent="+"+q[2]+" XP";$("enemies").innerHTML=Object.values(s.enemies).map(e=>`<div class="chip"><b>👾 ${e.name}</b><small>побеждено: ${e.hits}</small></div>`).join("");$("loot").innerHTML=s.loot.map(x=>`<div class="chip"><b>💎 ${x.phrase}</b><small>${x.uses}/3 uses</small></div>`).join("");let z=["Tutorial Village","Daily Life City","Hobby District","Social Zone","Travel Hub","USA"];$("map").innerHTML=z.map((x,n)=>`<div class="zone ${n===i?"current":""} ${n>i?"locked":""}">${n>i?"🔒":"📍"} <b>${x}</b><small>${n>i?"Locked":"Open"}</small></div>`).join("")}
function toast(t){let x=$("toast");x.textContent=t;x.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.add("hidden"),1800)}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function addChat(t,c){$("chat").insertAdjacentHTML("beforeend",`<div class="bubble ${c}">${esc(t).replace(/\n/g,"<br>")}</div>`);$("chat").scrollTop=$("chat").scrollHeight}
async function askAI(text,quest=false){if(!s.settings.key){toast("Сначала добавь API key в ⚙️");return null}let prompt=`You are an English RPG Game Master for a Russian-speaking A2 learner. Goal: conversational English for travel to the USA. Interests: guitar, chess, workouts, games and everyday life. Keep English simple. Correct only 1-3 important errors and explain them briefly in Russian. Give one useful phrase and one tiny challenge. Never shame mistakes. ${quest?"Quest: "+QUESTS[s.quest%QUESTS.length][0]+" — "+QUESTS[s.quest%QUESTS.length][1]:""} Learner: ${text}`;try{let r=await fetch(s.settings.endpoint,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+s.settings.key},body:JSON.stringify({model:s.settings.model,messages:[{role:"system",content:prompt}],temperature:.5})});let raw=await r.text();if(!r.ok)throw Error("HTTP "+r.status+": "+raw.slice(0,300));return JSON.parse(raw).choices?.[0]?.message?.content||"No AI response."}catch(e){return "AI error: "+e.message}}
$("settingsBtn").onclick=()=>{$("apiEndpoint").value=s.settings.endpoint;$("apiModel").value=s.settings.model;$("apiKey").value=s.settings.key;$("settingsModal").classList.remove("hidden")};
function closeSettings(){$("settingsModal").classList.add("hidden")}
$("closeSettings").onclick=closeSettings;$("cancelSettings").onclick=closeSettings;
$("saveSettings").onclick=()=>{s.settings.endpoint=$("apiEndpoint").value.trim();s.settings.model=$("apiModel").value.trim();s.settings.key=$("apiKey").value.trim();save();closeSettings();toast("✅ Настройки сохранены")};
$("clearKey").onclick=()=>{s.settings.key="";save();$("apiKey").value="";toast("API key удалён")};
$("resetApp").onclick=()=>{if(confirm("Сбросить весь прогресс?")){localStorage.removeItem(KEY);location.reload()}};
$("finishQuest").onclick=()=>{markDay();if(s.doneDate===today()){toast("Квест уже выполнен сегодня");return}let q=QUESTS[s.quest%QUESTS.length];s.doneDate=today();s.quest++;gain(q[2],q[3])};
$("checkQuest").onclick=async()=>{let v=$("answerBox").value.trim();if(!v){toast("Напиши ответ");return}$("checkQuest").disabled=true;$("checkQuest").textContent="🤖 Проверяю...";let out=await askAI(v,true);$("checkQuest").disabled=false;$("checkQuest").textContent="🤖 Проверить с ИИ";if(out){$("questFeedback").textContent=out;$("questFeedback").classList.remove("hidden");markDay();if(s.doneDate!==today()){let q=QUESTS[s.quest%QUESTS.length];s.doneDate=today();s.quest++;gain(q[2],q[3])}}};
async function send(){let v=$("chatInput").value.trim();if(!v)return;$("chatInput").value="";addChat(v,"user");addChat("Thinking...","ai");let out=await askAI(v);$("chat").lastElementChild.remove();addChat(out||"No response.","ai");if(out)gain(10,"speaking")}
$("sendChat").onclick=send;$("chatInput").onkeydown=e=>{if(e.key==="Enter")send()};render();